/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "mixpost.login": [],
    "mixpost.": [],
    "mixpost.installation": [],
    "mixpost.two-factor.login": [],
    "mixpost.password.request": [],
    "mixpost.password.email": [],
    "mixpost.password.reset": [
        {
            "name": "token"
        }
    ],
    "mixpost.password.store": [],
    "mixpost.logout": [],
    "mixpost.home": [],
    "mixpost.profile.index": [],
    "mixpost.profile.updatePreferences": [],
    "mixpost.profile.updateUser": [],
    "mixpost.profile.updatePassword": [],
    "mixpost.profile.confirmPassword": [],
    "mixpost.profile.ensurePasswordConfirmed": [],
    "mixpost.profile.two-factor-auth.enable": [],
    "mixpost.profile.two-factor-auth.confirm": [],
    "mixpost.profile.two-factor-auth.showRecoveryCodes": [],
    "mixpost.profile.two-factor-auth.regenerateRecoveryCodes": [],
    "mixpost.profile.two-factor-auth.disable": [],
    "mixpost.profile.accessTokens.index": [],
    "mixpost.profile.accessTokens.store": [],
    "mixpost.profile.accessTokens.delete": [
        {
            "name": "token"
        }
    ],
    "mixpost.profile.accessTokens.deleteMultiple": [],
    "mixpost.extractUrlMeta": [],
    "mixpost.dashboardAdmin": [],
    "mixpost.workspaces.index": [],
    "mixpost.workspaces.create": [],
    "mixpost.workspaces.store": [],
    "mixpost.workspaces.view": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.workspaces.edit": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.workspaces.update": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.workspaces.delete": [
        {
            "name": "workspace",
            "binding": "uuid"
        }
    ],
    "mixpost.workspaces.deleteMultiple": [],
    "mixpost.workspaces.resources.items": [],
    "mixpost.workspaces.users.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.workspaces.users.update": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.workspaces.users.delete": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.users.index": [],
    "mixpost.users.create": [],
    "mixpost.users.store": [],
    "mixpost.users.view": [
        {
            "name": "user"
        }
    ],
    "mixpost.users.edit": [
        {
            "name": "user"
        }
    ],
    "mixpost.users.update": [
        {
            "name": "user"
        }
    ],
    "mixpost.users.delete": [
        {
            "name": "user"
        }
    ],
    "mixpost.users.deleteMultiple": [],
    "mixpost.users.resources.items": [],
    "mixpost.services.index": [],
    "mixpost.services.update": [
        {
            "name": "service"
        }
    ],
    "mixpost.services.createMastodonApp": [],
    "mixpost.pages.index": [],
    "mixpost.pages.create": [],
    "mixpost.pages.store": [],
    "mixpost.pages.edit": [
        {
            "name": "page"
        }
    ],
    "mixpost.pages.update": [
        {
            "name": "page"
        }
    ],
    "mixpost.pages.delete": [
        {
            "name": "page"
        }
    ],
    "mixpost.pages.deleteMultiple": [],
    "mixpost.pages.generateSamples": [],
    "mixpost.blocks.store": [],
    "mixpost.blocks.update": [
        {
            "name": "block"
        }
    ],
    "mixpost.blocks.delete": [
        {
            "name": "block"
        }
    ],
    "mixpost.configs.theme.form": [],
    "mixpost.configs.theme.update": [],
    "mixpost.configs.ai.form": [],
    "mixpost.configs.ai.update": [],
    "mixpost.system.webhooks.index": [],
    "mixpost.system.webhooks.create": [],
    "mixpost.system.webhooks.store": [],
    "mixpost.system.webhooks.edit": [
        {
            "name": "webhook"
        }
    ],
    "mixpost.system.webhooks.update": [
        {
            "name": "webhook"
        }
    ],
    "mixpost.system.webhooks.delete": [
        {
            "name": "webhook"
        }
    ],
    "mixpost.system.webhooks.deleteMultiple": [],
    "mixpost.system.webhooks.updateSecret": [
        {
            "name": "webhook"
        }
    ],
    "mixpost.system.webhooks.deliveries.index": [
        {
            "name": "webhook"
        }
    ],
    "mixpost.system.webhooks.deliveries.show": [
        {
            "name": "webhook"
        },
        {
            "name": "delivery"
        }
    ],
    "mixpost.system.webhooks.deliveries.resend": [
        {
            "name": "webhook"
        },
        {
            "name": "delivery"
        }
    ],
    "mixpost.system.status": [],
    "mixpost.system.logs.index": [],
    "mixpost.system.logs.download": [],
    "mixpost.system.logs.clear": [],
    "mixpost.files.upload": [],
    "mixpost.dashboard": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.switchWorkspace": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.reports": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.accounts.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.accounts.add": [
        {
            "name": "workspace"
        },
        {
            "name": "provider"
        }
    ],
    "mixpost.accounts.update": [
        {
            "name": "workspace"
        },
        {
            "name": "account"
        }
    ],
    "mixpost.accounts.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "account"
        }
    ],
    "mixpost.accounts.updateSuffix": [
        {
            "name": "workspace"
        },
        {
            "name": "account"
        }
    ],
    "mixpost.accounts.entities.index": [
        {
            "name": "workspace"
        },
        {
            "name": "provider"
        }
    ],
    "mixpost.accounts.entities.store": [
        {
            "name": "workspace"
        },
        {
            "name": "provider"
        }
    ],
    "mixpost.postingSchedule.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.postingSchedule.update": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.webhooks.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.webhooks.create": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.webhooks.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.webhooks.edit": [
        {
            "name": "workspace"
        },
        {
            "name": "webhook"
        }
    ],
    "mixpost.webhooks.update": [
        {
            "name": "workspace"
        },
        {
            "name": "webhook"
        }
    ],
    "mixpost.webhooks.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "webhook"
        }
    ],
    "mixpost.webhooks.deleteMultiple": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.webhooks.updateSecret": [
        {
            "name": "workspace"
        },
        {
            "name": "webhook"
        }
    ],
    "mixpost.webhooks.deliveries.index": [
        {
            "name": "workspace"
        },
        {
            "name": "webhook"
        }
    ],
    "mixpost.webhooks.deliveries.show": [
        {
            "name": "workspace"
        },
        {
            "name": "webhook"
        },
        {
            "name": "delivery"
        }
    ],
    "mixpost.webhooks.deliveries.resend": [
        {
            "name": "workspace"
        },
        {
            "name": "webhook"
        },
        {
            "name": "delivery"
        }
    ],
    "mixpost.posts.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.posts.create": [
        {
            "name": "workspace"
        },
        {
            "name": "schedule_at"
        }
    ],
    "mixpost.posts.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.posts.edit": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.posts.update": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.posts.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.posts.schedule": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.posts.addToQueue": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.posts.duplicate": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.posts.restore": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.posts.deleteMultiple": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.calendar": [
        {
            "name": "workspace"
        },
        {
            "name": "date"
        },
        {
            "name": "type"
        }
    ],
    "mixpost.media.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.media.delete": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.media.fetchUploads": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.media.fetchStock": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.media.fetchGifs": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.media.download": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.media.upload": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.tags.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.tags.update": [
        {
            "name": "workspace"
        },
        {
            "name": "tag"
        }
    ],
    "mixpost.tags.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "tag"
        }
    ],
    "mixpost.hashtaggroups.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.hashtaggroups.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.hashtaggroups.update": [
        {
            "name": "workspace"
        },
        {
            "name": "hashtaggroup"
        }
    ],
    "mixpost.hashtaggroups.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "hashtaggroup"
        }
    ],
    "mixpost.variables.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.variables.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.variables.update": [
        {
            "name": "workspace"
        },
        {
            "name": "variable"
        }
    ],
    "mixpost.variables.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "variable"
        }
    ],
    "mixpost.templates.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.templates.create": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.templates.edit": [
        {
            "name": "workspace"
        },
        {
            "name": "template"
        }
    ],
    "mixpost.templates.api.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.templates.api.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.templates.api.update": [
        {
            "name": "workspace"
        },
        {
            "name": "template"
        }
    ],
    "mixpost.templates.api.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "template"
        }
    ],
    "mixpost.ai.text.generate": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.ai.text.modify": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.provider.pinterest.storeBoard": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.callbackSocialProvider": [
        {
            "name": "provider"
        }
    ],
    "mixpost.manifest": [],
    "mixpost.pages.show": [
        {
            "name": "slug"
        }
    ],
    "mixpost.api.accounts.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.accounts.show": [
        {
            "name": "workspace"
        },
        {
            "name": "account"
        }
    ],
    "mixpost.api.posts.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.posts.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.posts.show": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.api.posts.update": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.api.posts.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.api.posts.deleteMultiple": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.posts.schedule": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.api.posts.addToQueue": [
        {
            "name": "workspace"
        },
        {
            "name": "post"
        }
    ],
    "mixpost.api.media.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.media.show": [
        {
            "name": "workspace"
        },
        {
            "name": "media"
        }
    ],
    "mixpost.api.media.upload": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.media.delete": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.tags.index": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.tags.store": [
        {
            "name": "workspace"
        }
    ],
    "mixpost.api.tags.show": [
        {
            "name": "workspace"
        },
        {
            "name": "tag"
        }
    ],
    "mixpost.api.tags.update": [
        {
            "name": "workspace"
        },
        {
            "name": "tag"
        }
    ],
    "mixpost.api.tags.delete": [
        {
            "name": "workspace"
        },
        {
            "name": "tag"
        }
    ],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag"
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag"
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id"
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.index": [
        {
            "name": "view"
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": []
}
}
export {};
